name: Test Workflow
on:
  push:


jobs:
    test:
        strategy:
            matrix:
                go-version: [1.17, 1.18, 1.19]

    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

    steps:
    - name: Set up ${{ matrix.go-version}}
      uses: actions/setup-go@v4
      with:
        go-verion: ${{matrix.go-version}}

    - name: Run tests
      uses: go test ./...
   

    

    